## Lab 3: pandas

#### Introduction

We will examine a dataset containing characteristics of lego sets manufactured between 1961 and 2019 from the BRICKSET website. Variables in the dataset are described below.

| VARIABLE             |      DESCRIPTION             |
|:----------|:-------------|
| ID |  set id |
| Name |    name of set   |
| Themegroup | themegroup of set |
| Theme |  theme of set |
| Subtheme |    subtheme of set   |
| Year | year released |
| Pieces |  number of pieces |
| Minifig |    number of minifigs   |
| Package | type of packaging |
| Retail_Price |  recommended retail pri



Load pandas to read in the data and save it as dataframe named lego.

In [14]:
import pandas as pd

lego = pd.read_csv('lego.csv')
print(lego)
lego.loc[lego.retail_price == 0, :].head(7)

                id                      name     themegroup           theme  \
0      100STORES-1     100 Stores minifigure  Miscellaneous     Promotional
1          10264-1             Corner Garage   Model making  Creator Expert
2          10265-1              Ford Mustang   Model making  Creator Expert
3          10766-1                Woody & RC       Licensed       Toy Story
4          10769-1               RV Vacation       Licensed       Toy Story
...            ...                       ...            ...             ...
12209       1240-2              8 Road Signs          Basic          System
12210       1241-2              8 Road Signs          Basic          System
12211       1247-2           Esso Pumps/Sign          Basic          System
12212       1248-2  Painted Trees and Bushes          Basic          System
12213       1300-1   Lego Mosaik Set (Small)          Basic          System

                subtheme    year  pieces  minifigs       package  retail_price
0      LEGO brand stores  2019.0     NaN         0  Blister pack           NaN
1      Modular Buildings  2019.0  2569.0         6           Box        199.99
2               Vehicles  2019.0  1471.0         0           Box        149.99
3            Toy Story 4  2019.0    69.0         0           Box          9.99
4            Toy Story 4  2019.0   178.0         0           Box         34.99
...                  ...     ...     ...       ...           ...           ...
12209       Supplemental  1955.0     NaN         0           NaN           NaN
12210       Supplemental  1955.0     NaN         0           NaN           NaN
12211       Supplemental  1955.0     NaN         0           NaN           NaN
12212       Supplemental  1955.0     NaN         0           NaN           NaN
12213             Mosaic  1955.0     NaN         0           NaN           NaN

[12214 rows x 10 columns]

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
2266,40135-1,Angler Fish,Miscellaneous,Promotional,Monthly Mini Model Build,2015.0,29.0,0,Polybag,0.0
2269,40138-1,Christmas Train,Miscellaneous,Seasonal,Christmas,2015.0,233.0,0,Box,0.0
2882,40094-1,Snowplough,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,46.0,0,Polybag,0.0
2883,40095-1,Micro Manager,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,50.0,0,NaN,0.0
2884,40096-1,Spring Tree,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,62.0,0,Polybag,0.0
2885,40097-1,Helicopter,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,44.0,0,Polybag,0.0
2886,40098-1,Dragon,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,43.0,0,Polybag,0.0

#### Question 1:
Some sets have missing information for retail_price or pieces or both. This could be because the sets are free (giveaways), they aren’t traditional lego sets (comic books, etc) or just because the information is missing. Filter the lego dataset based on the specifications below and save the result as lego. Hence, you will overwrite the original lego object. In addition, describe the implications of removing these sets.

Your new lego (data frame) should have:

• no missing pieces

• only contain sets with a nonzero number of pieces

• no missing retail_price

• only contain sets with a nonzero retail_price

• no missing year

- Print out the shape of the dataframe after cleaning the dataset.
-

In [16]:
print(lego.shape)
lego2 = lego.dropna()
print(lego2.shape)
lego2 = lego2.loc[lego2.retail_price > 0 , :]
print(lego2.shape)
print (lego2.describe())

(12214, 10)
(4360, 10)
(4277, 10)
              year       pieces     minifigs  retail_price
count  4277.000000  4277.000000  4277.000000   4277.000000
mean   2008.243395   251.114099     2.110592     29.231814
std       9.602551   433.553512     2.479037     41.633822
min    1961.000000     1.000000     0.000000      0.500000
25%    2002.000000    38.000000     0.000000      4.990000
50%    2012.000000   109.000000     1.000000     14.990000
75%    2015.000000   305.000000     3.000000     38.500000
max    2019.000000  7541.000000    28.000000    799.990000

#### Question 2:	
Arrange the dataset in descending order of retail_price and print the first three rows. Report in words the names of the three most expensive lego sets, their prices, and how many pieces each has.

In [27]:
lego2.sort_values(by='retail_price', ascending=False).tail(3)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
12082,805-2,3 Little Indians,Vintage themes,Samsonite,Model Maker,1964.0,89.0,0,Blister pack,0.98
12091,520-4,2 X 2 Plate (Flat Roof Bricks with 4 Studs),Vintage themes,Samsonite,Supplemental,1961.0,40.0,0,Box,0.50
12106,215-3,2 X 8 Bricks,Vintage themes,Samsonite,Supplemental,1961.0,9.0,0,Box,0.50

#### Question 3:

It appears that the most expensive sets generally have more pieces. Create a new variable (column) price_per_piece, representing the price in dollars per piece for each of the sets. Save the result as lego2. Hence, you will overwrite the current lego object.

In [34]:
#Not the question's answers
lego2.theme.unique()
lego2.loc[lego2.theme == 'Harry Potter', :].sample(6)
lego2.loc[lego2.theme == 'Harry Potter', ['name' , 'themegroup' , 'theme' , 'subtheme']].sample(6)

lego2['price_per_piece'] = lego2.retail_price / lego2.pieces
lego2.sample(6)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price,price_per_piece
7267,4511-1,High Speed Train,Modern day,World City,Trains,2003.0,336.0,3,Box,90.00,0.267857
6596,65766-1,Thomas Bridge & Tunnel Set,Pre-school,Duplo,Product Collection,2005.0,87.0,0,Box,70.00,0.804598
1363,71018-5,Veterinarian,Miscellaneous,Collectable Minifigures,Series 17,2017.0,5.0,1,Foil pack,3.99,0.798000
4344,9456-1,Spinner Battle Arena,Action/Adventure,Ninjago,Spinners,2012.0,418.0,2,Box,39.99,0.095670
1554,10725-1,Lost Temple,Junior,Juniors,Ninjago,2016.0,172.0,3,Box,29.99,0.174360
967,10857-1,Piston Cup Race,Pre-school,Duplo,Cars 3,2017.0,31.0,3,Box,29.99,0.967419

#### Question 4:	

Arrange the lego2 dataset in descending order of price_per_piece and return only the columns: name, themegroup, theme, pieces, price_per_piece, and the first five rows. What do you notice about these sets?

In [37]:
lego2.sort_values(by='price_per_piece', ascending=False).loc[:, ['name', 'themegroup', 'theme' , 'pieces' ,'price_per_piece']].head(5)

,name,themegroup,theme,pieces,price_per_piece
5551,Rechargeable Battery Box,Technical,Power Functions,1.0,49.990
5553,Transformer 10V DC,Technical,Power Functions,1.0,29.990
5616,Collectable Display Set 2,Licensed,Star Wars,2.0,24.995
8694,Temperature Sensor,Technical,Mindstorms,1.0,24.000
7540,Robotics Invention System Upgrade Kit,Technical,Mindstorms,1.0,20.000

#### Question 5:

What is the mean price_per_piece for the top 40 'Star Wars' sets in terms of price_per_piece?

In [42]:
sw_mean = lego2.loc[lego2.theme == 'Star Wars', :].retail_price.mean()
ts_mean = lego2.loc[lego2.theme == 'Toy Story', :].retail_price.mean()

print(sw_mean)
print(ts_mean)

51.56355421686747
36.32333333333334

#### Question 6:

What are the unique themes in the lego dataset?

In [43]:
lego2.theme.unique()

array(['Creator Expert', 'Toy Story', 'Duplo', 'Architecture',
       'Minecraft', 'Ideas', 'City', 'BrickHeadz', 'Ninjago',
       'The Lego Movie 2: The Second Part', 'Star Wars',
       'Speed Champions', 'Jurassic World', 'Marvel Super Heroes',
       'DC Comics Super Heroes', 'Classic', 'Juniors', 'Wizarding World',
       'Creator', 'Miscellaneous', 'Seasonal', 'Promotional', 'Disney',
       'Unikitty', 'Friends', 'The LEGO Ninjago Movie',
       'Collectable Minifigures', 'Nexo Knights', 'The LEGO Batman Movie',
       'Pirates of the Caribbean', 'Dimensions', 'Mixels', 'Bionicle',
       'Legends of Chima', 'Education', 'Teenage Mutant Ninja Turtles',
       'The LEGO Movie', 'The Hobbit', 'The Lord of the Rings', 'Space',
       'Mindstorms', 'Games', 'Castle', 'Monster Fighters',
       'Bricks and More', 'Cars', 'Harry Potter', 'Racers',
       'Power Functions', 'Indiana Jones', 'Pirates', 'Factory',
       'Exo-Force', 'Trains', 'Sports', 'Town', 'World City',
       'Alpha Team', 'Spider-Man', 'Bulk Bricks', 'Explore',
       'Adventurers', 'Studios', 'Western', 'Technic', 'Basic',
       'Aquazone', 'Service Packs', 'Time Cruisers', 'Assorted', 'Books',
       'Samsonite', 'LEGOLAND'], dtype=object)