## Lab 3: pandas

#### Introduction

We will examine a dataset containing characteristics of lego sets manufactured between 1961 and 2019 from the BRICKSET website. Variables in the dataset are described below.

| VARIABLE             |      DESCRIPTION             |
|:----------|:-------------|
| ID |  set id |
| Name |    name of set   |
| Themegroup | themegroup of set |
| Theme |  theme of set |
| Subtheme |    subtheme of set   |
| Year | year released |
| Pieces |  number of pieces |
| Minifig |    number of minifigs   |
| Package | type of packaging |
| Retail_Price |  recommended retail pri



Load pandas to read in the data and save it as dataframe named lego.

In [2]:
import pandas as pd

lego = pd.read_csv('lego.csv')
print(lego)
lego.loc[lego.retail_price == 0, :].head(7)

                id                      name     themegroup           theme  \
0      100STORES-1     100 Stores minifigure  Miscellaneous     Promotional
1          10264-1             Corner Garage   Model making  Creator Expert
2          10265-1              Ford Mustang   Model making  Creator Expert
3          10766-1                Woody & RC       Licensed       Toy Story
4          10769-1               RV Vacation       Licensed       Toy Story
...            ...                       ...            ...             ...
12209       1240-2              8 Road Signs          Basic          System
12210       1241-2              8 Road Signs          Basic          System
12211       1247-2           Esso Pumps/Sign          Basic          System
12212       1248-2  Painted Trees and Bushes          Basic          System
12213       1300-1   Lego Mosaik Set (Small)          Basic          System

                subtheme    year  pieces  minifigs       package  retail_price
0      LEGO brand stores  2019.0     NaN         0  Blister pack           NaN
1      Modular Buildings  2019.0  2569.0         6           Box        199.99
2               Vehicles  2019.0  1471.0         0           Box        149.99
3            Toy Story 4  2019.0    69.0         0           Box          9.99
4            Toy Story 4  2019.0   178.0         0           Box         34.99
...                  ...     ...     ...       ...           ...           ...
12209       Supplemental  1955.0     NaN         0           NaN           NaN
12210       Supplemental  1955.0     NaN         0           NaN           NaN
12211       Supplemental  1955.0     NaN         0           NaN           NaN
12212       Supplemental  1955.0     NaN         0           NaN           NaN
12213             Mosaic  1955.0     NaN         0           NaN           NaN

[12214 rows x 10 columns]

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
2266,40135-1,Angler Fish,Miscellaneous,Promotional,Monthly Mini Model Build,2015.0,29.0,0,Polybag,0.0
2269,40138-1,Christmas Train,Miscellaneous,Seasonal,Christmas,2015.0,233.0,0,Box,0.0
2882,40094-1,Snowplough,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,46.0,0,Polybag,0.0
2883,40095-1,Micro Manager,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,50.0,0,NaN,0.0
2884,40096-1,Spring Tree,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,62.0,0,Polybag,0.0
2885,40097-1,Helicopter,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,44.0,0,Polybag,0.0
2886,40098-1,Dragon,Miscellaneous,Promotional,Monthly Mini Model Build,2014.0,43.0,0,Polybag,0.0

#### Question 1:
Some sets have missing information for retail_price or pieces or both. This could be because the sets are free (giveaways), they aren’t traditional lego sets (comic books, etc) or just because the information is missing. Filter the lego dataset based on the specifications below and save the result as lego. Hence, you will overwrite the original lego object. In addition, describe the implications of removing these sets.

Your new lego (data frame) should have:

• no missing pieces

• only contain sets with a nonzero number of pieces

• no missing retail_price

• only contain sets with a nonzero retail_price

• no missing year

- Print out the shape of the dataframe after cleaning the dataset.
-

In [3]:
# dropna: remove rows with missing values in 'pieces', 'retail_price', or 'year' 
print(f"The shape of the lego dataset is: {lego.shape}")

lego_cleaned=lego.dropna()
print(f"The shape of the cleaned lego dataset is: {lego_cleaned.shape}")

lego_cleaned=lego_cleaned.loc[lego_cleaned.retail_price>0,:] #subsetting, keeps anything>0
print(f"The shape of the updated cleaned lego dataset is: {lego_cleaned.shape}")

The shape of the lego dataset is: (12214, 10)
The shape of the cleaned lego dataset is: (4360, 10)
The shape of the updated cleaned lego dataset is: (4277, 10)

#### Question 2:	
Arrange the dataset in descending order of retail_price and print the first three rows. Report in words the names of the three most expensive lego sets, their prices, and how many pieces each has.

In [4]:
lego_cleaned.sort_values(by='retail_price', ascending=False).head(3)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
1434,75192-1,Millennium Falcon,Licensed,Star Wars,Ultimate Collector Series,2017.0,7541.0,8,Box,799.99
5944,10179-1,Ultimate Collector's Millennium Falcon,Licensed,Star Wars,Ultimate Collector Series,2007.0,5197.0,5,Box,499.99
2065,75159-1,Death Star,Licensed,Star Wars,Ultimate Collector Series,2016.0,4016.0,27,Box,499.99

#### Question 3:

It appears that the most expensive sets generally have more pieces. Create a new variable (column) price_per_piece, representing the price in dollars per piece for each of the sets. Save the result as lego2. Hence, you will overwrite the current lego object.

In [5]:
lego_cleaned['price_per_piece'] = lego_cleaned.retail_price / lego_cleaned.pieces
lego_cleaned.sample(6)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price,price_per_piece
3117,60055-1,Monster Truck,Modern day,City,Traffic,2014.0,78.0,1,Box,9.99,0.128077
628,60174-1,Mountain Police Headquarters,Modern day,City,Mountain Police,2018.0,663.0,7,Box,89.99,0.135732
648,60196-1,Arctic Supply Plane,Modern day,City,Arctic,2018.0,707.0,4,Box,79.99,0.113140
7249,4478-1,Geonosian Fighter,Licensed,Star Wars,Episode II,2003.0,170.0,4,Box,20.00,0.117647
3827,79006-1,The Council of Elrond,Licensed,The Lord of the Rings,The Fellowship of the Ring,2013.0,243.0,4,Box,29.99,0.123416
4592,3858-1,Waldurk Forest,Miscellaneous,Games,Heroica,2011.0,225.0,7,Box,19.99,0.088844

#### Question 4:	

Arrange the lego2 dataset in descending order of price_per_piece and return only the columns: name, themegroup, theme, pieces, price_per_piece, and the first five rows. What do you notice about these sets?

In [6]:
lego_sorted = lego_cleaned.sort_values(by='price_per_piece', ascending=False)
lego_sorted= lego_sorted.loc[: ,['name', 'themegroup', 'theme', 'pieces', 'price_per_piece']]
lego_sorted.head(5)

,name,themegroup,theme,pieces,price_per_piece
5551,Rechargeable Battery Box,Technical,Power Functions,1.0,49.990
5553,Transformer 10V DC,Technical,Power Functions,1.0,29.990
5616,Collectable Display Set 2,Licensed,Star Wars,2.0,24.995
8694,Temperature Sensor,Technical,Mindstorms,1.0,24.000
7540,Robotics Invention System Upgrade Kit,Technical,Mindstorms,1.0,20.000

#### Question 5:

What is the mean price_per_piece for the top 40 'Star Wars' sets in terms of price_per_piece?

In [7]:
lego_sorted.loc[lego_sorted.theme=='Toy Story', :].head(40).price_per_piece.mean()

0.16089862892544177

#### Question 6:

What are the unique themes in the lego dataset?

In [9]:
lego.theme.value_counts()

theme
Duplo                        1050
Town                          640
Star Wars                     631
Gear                          585
Collectable Minifigures       565
                             ...
Avatar The Last Airbender       2
Primo                           2
The Simpsons                    2
Boost                           1
CITY                            1
Name: count, Length: 139, dtype: int64